language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn test
deploy:
  provider: npm
  email: ekaragodin@gmail.com
  api_key:
    secure: NL2+QCtZ27o2y2y9Z21fYjzO3aiBxHcWlGSEuEyrlDguweXwIMJVNb8v9AsGZPms4SzkX/QqNH/VoH5DeKSAnu59FtVDalokVIZSGpoBF8RO+kqUE2AZbXpel7lw5+IhZ/4q3AAqe0nfCP7zkqD8Jy180THrckHRl7i0b6+3zpTVNg7YKK0BZEFcH45vgIjfpSDqHvnEMsgTW2x44r4119gXihH91nTuzmZDPgf3Gmfnb7yC+pGdfN8bUqaHbSADrJBrLvFhhHxknhVJYT2gEwxCPEZMv29nmK2N+PU0muzBEHXi/FmI6wGceBiH0eizvm7z+W02xLbFla3IECqjBxEC3ASwJVJmvEHsHyoNi40850VMJQoeYLsiKdX31pU7G/FfGc9+NNE1goyRYN1GRh2Ko6ECreWod0uQgS3jk9EAhpWG8JQ152kPToJy4ORV7nMkayVMM5mNWj5SQJsuFSJayC+HeoMcox1cyad9hP1QXBoFV7uyKNp8ztKlP/UzhXLEHx/d9JCqca3WNUyKRcHz1lHubiFV1Xplk3jiiRiRKOlv8YXxKMZqHO1LxKcMmp/fm4x8Kh6OX6Q76CxrowLd65ZWjQ1SJh8KFC06F1C9dNOALxj+pXlfz+02E3otKDQ5/0tdMOTAL0qjomKA+dY0IMRuXxPBg6v0AYzf+so=
  skip_cleanup: true
  on:
    tags: true
    repo: plesk/plesk-ext-sdk
    branch: master
